# Generated by Django 5.0.6 on 2024-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_sem',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
